### ISSUE TITLE
Is it possible you add a pause and resume method

### ISSUE THREAD

**Issue by StyleandCode** [shts/StoriesProgressView#1]
Hi, i really love your library, was just wondering if you could add methods so that a user can long press to pause , then leave to resume.
Best Regards

**Comment by shts** [comment]
Thank you! I will do my best.

**Comment by shts** [comment]
@StyleandCode released 2.00 impl pasue() and resume()!

**Comment by StyleandCode** [comment]
hhahahhahhaha...you are a Champ. Thank you Soo much. Perfect product.
Hope videos would come in soon to.
Thanks a lot Boss
