### ISSUE TITLE
Could you add support for videos as well?

### ISSUE THREAD

**Issue by anubhavmalik** [shts/StoriesProgressView#19]

**Comment by mbf5923** [comment]
i have the same problem with video and StoriesProgressView
when i play the video on story, peogress not work as well

**Comment by maximus9600** [comment]
Could you provide a better description of what you implemented and what you faced? I have tried this library with video and it works fine.

**Comment by bstillitano** [comment]
@maximus9600 can you provide a sample video implementation?

**Comment by jonataslaw** [comment]
> Could you provide a better description of what you implemented and what you faced? I have tried this library with video and it works fine.

Please, can you provide a sample video implementation?

**Comment by anubhavmalik** [comment]
@jonataslaw , sorry for the late reply. I don't have the code anymore because I left the project. But the frame sync was lagging I remember. But since I am not using it anymore I'll mark it as closed.
